### ISSUE TITLE
Does not appear to be compatible with CubeRoot

### ISSUE THREAD

**Issue by numbermaniac** [RuleBasedIntegration/Rubi#1]
You may remember from [this answer of yours](https://mathematica.stackexchange.com/a/175617/47323) that the following works perfectly:

![screen shot 2018-07-16 at 6 13 35 pm](https://user-images.githubusercontent.com/5206120/42748571-0540718e-8924-11e8-905e-71494cf0b0af.png)

However, if I write this same expression using the `CubeRoot` function, it does not work:

![screen shot 2018-07-16 at 6 14 36 pm](https://user-images.githubusercontent.com/5206120/42748617-306e6884-8924-11e8-872f-f733df42994f.png)

**Comment by halirutan** [comment]
The main reason is (to quote Albert) that Rubi knows nothing about `CubeRoot`. This symbol, its meaning and therefore rules for it are not part of Rubi at the moment. Additionally, both representations are not equivalent and therefore, transformation rules might not be correct if you simply switch one with the other. Especially since the argument of `CubeRoot` is assumed to be real-valued while `x^(1/3)` can be complex.

Maybe Albert comments here as well, but as for now, the short answer is that rules for `CubeRoot` are not implemented.
