### ISSUE TITLE
Expression cannot be integrated if it is simplified beforehand

### ISSUE THREAD

**Issue by halirutan** [RuleBasedIntegration/Rubi#11]
When we calculate the derivative of the following expression, Rubi can integrate it back to its initial form

```mma
expr = 2 Sqrt[x + Log[x]] + 2 Log[x + Sqrt[x + Log[x]]];
dExpr = D[expr, x];
Int[dExpr, x]

(* Out[17]= 2 Sqrt[x + Log[x]] + 2 Log[x + Sqrt[x + Log[x]]] *)
```
However, if we simplify `dExpr` before integration, this is no longer possible

![Mathematica graphics](http://i.stack.imgur.com/GBKf4.png)

Similary, for this form of `dExpr` the antiderivative can also not be found.

![integrate](https://user-images.githubusercontent.com/511683/48521158-95635c00-e873-11e8-9b00-c0f17412d690.png)

**Comment by AlbertRich** [comment]
Instead of an easily integrable sum, `FullSimplify` puts `dExpr` over a common denominator (`Together` would do the same).  The resulting form is outside the class of expression for which Rubi has integration rules.  BTW, Mathematica 11.3 also cannot integrate `dExpr` when put over a common denominator.

As you probably know, multiplying large primes is relatively trivial; however, factoring the result can be extremely difficult (a fact used by the RSA and other public-key encryption systems).  Similarly, differentiation is relatively trivial; however, integrating the resulting derivative can be extremely difficult.

So it's easy to come with integrable expressions, like the ones above, that will trip-up any symbolic integrator, including Rubi.  Just differentiate random expressions, and put the resulting derivatives over a common denominator or otherwise transform it into a more complicated form.

The Risch and other advanced algorithms can guaranteeably integrate certain classes of expressions (e.g. all rational functions).  However, they often return huge, incomprehensible antiderivative as the [integration test-suite results](https://rulebasedintegration.org/testResults.html) on computer algebra systems that incorporate such advanced algorithms show.

So when faced with an integration problem, I recommend first trying Rubi to see if it finds a simple antiderivative in steps a human can understand.  If that fails, then hit the problem with an integrator that uses advanced algorithms.

**Comment by axkr** [comment]
Probably not an easy task, but you may give `FullSimplify` more "guidance" with a modified `ComplexityFunction`.

Maybe by modifying the `SimplifyCount` functions at the end of this page?
* https://reference.wolfram.com/language/ref/ComplexityFunction.html
