### ISSUE TITLE
EqQ sometimes called with only one argument

### ISSUE THREAD

**Issue by axkr** [RuleBasedIntegration/Rubi#28]
Found these lines, where EqQ is called with only one argument. But where seem to be no definition for only one argument.

`EqQ[m + 1/2]` in this line
- https://github.com/RuleBasedIntegration/Rubi/blob/26b65aa1e3adf733511df3a4d7ffb2d8709a5a9d/Rubi/IntegrationRules/1%20Algebraic%20functions/1.2%20Trinomial%20products/1.2.4%20Improper/1.2.4.2%20(d%20x)%5Em%20(a%20x%5Eq%2Bb%20x%5En%2Bc%20x%5E(2%20n-q))%5Ep.m#L7

`EqQ[m - 2*n + 1]` in these lines:
- https://github.com/RuleBasedIntegration/Rubi/blob/26b65aa1e3adf733511df3a4d7ffb2d8709a5a9d/Rubi/IntegrationRules/6%20Hyperbolic%20functions/6.1%20Hyperbolic%20sine/6.1.12%20(e%20x)%5Em%20(a%2Bb%20sinh(c%2Bd%20x%5En))%5Ep.m#L38
- https://github.com/RuleBasedIntegration/Rubi/blob/26b65aa1e3adf733511df3a4d7ffb2d8709a5a9d/Rubi/IntegrationRules/6%20Hyperbolic%20functions/6.1%20Hyperbolic%20sine/6.1.12%20(e%20x)%5Em%20(a%2Bb%20sinh(c%2Bd%20x%5En))%5Ep.m#L39

**Comment by AlbertRich** [comment]
Thanks axkr for reporting these deficiencies in Rubi 4.16.1.  They were introduced when converting Rubi from using `ZeroQ[u]` to `EqQ[u,0]`.  Turns out they are harmless, and so were not discovered by the integration test-suite.  If you wish to fix them anyway:
* In the file "1.2.4.2 (d x)^m (a x^q+b x^n+c x^(2 n-q))^p", simply delete `EqQ[m+1/2]  ||`.
* In the file "6.1.12 (e x)^m (a+b sinh(c+d x^n))^p", change the two occurrences of `EqQ[m-2*n+1]` to `EqQ[m-2*n+1,0]`.

Albert
