### ISSUE TITLE
Is it possible to add Tangent half-angle formula in the Rules?

### ISSUE THREAD

**Issue by wuyudi** [RuleBasedIntegration/Rubi#30]
Recently I came up with this :

```mathematica
Int[(x Sin[x]^3)/(Cos[x]^2 + 1), x] // Steps
```

Rubi failed to calculate it.

But if I use t=tan(x/2) , Tangent_half-angle_formula

```mathematica
Steps[Int[((2 ArcTan[t] ((2 t)/(1 + t^2))^3) D[2 ArcTan[t]])/(((
    1 - t^2)/(1 + t^2))^2 + 1), t]]
```

Rubi can work it out.

> But since there are many problems with things like `arctan(tan(x))` , so I don't know whether it will bring problems.

**Comment by AlbertRich** [comment]
To avoid the "many problems with things like arctan(tan(x))", instead of the tan theta/2 substitution better to simply expand the integrand
```mma
(x Sin[x]^3)/(Cos[x]^2 + 1)
```
to
```mma
(x Sin[x]^3)/(2 (1 - I Cos[x])) + (x Sin[x]^3)/(2 (1 + I Cos[x]))
```
which Rubi can integrate.  Unfortunately I see no way to avoid the introduction of the ugly imaginary unit.

I just added a new rule for the next release of Rubi that will integrate all expressions of the form
```mma
((e+f x)^m F[c+d x]^n)/(a+b Cos[c+d x]^2)
```
where F is any trig function and m and n are positive integers.  Also added analogous rules for the sine and for the hyperbolic sine and cosine.

Thanks for pointing out this low hanging fruit.
Albert
