### ISSUE TITLE
Problems Extracting Stats

### ISSUE THREAD

**Issue by rubgb** [RuleBasedIntegration/Rubi#8]
When I try in Mathematica 11.3
{stat, result} = Stats[Int[(a + b*Sqrt[x])^d, x]];

I get the following error message:

Set::shape: Lists {stat,result} and -((2 a (a+b Sqrt[x])^(1+d))/(b^2 (1+d)))+(2 (a+b Sqrt[x])^(2+d))/(b^2 (2+d)) are not the same shape.

Any alternatives?

**Comment by halirutan** [comment]
I'm sorry, this is my fault because I did not update the documentation on the website accordingly. We unified the behavior of `Stats`, `Steps`, and `Step`. This means, per default, all three functions will *print* their information because this is the most common use-case.

If you want to have the information *returned* in the form `{info, result}`, you can use the option `RubiPrintInformation -> False` with all three functions `Stats`, `Steps`, and `Step`. So for you this means you need to use

```mma
{stat, result} = Stats[Int[(a + b*Sqrt[x])^d, x], RubiPrintInformation -> False]
```

**Comment by rubgb** [comment]
Thanks for the clarification
