### ISSUE TITLE
Bibtex entry for citation

### ISSUE THREAD

**Issue by JedStephens** [RuleBasedIntegration/Rubi#9]
It would be useful to have a bibtex reference available on the https://rulebasedintegration.org/ site to make it easier (and also uniform) to reference the use of Rubi.

**Comment by halirutan** [comment]
I already discussed this with Albert some time ago, but it seems we kind of forgot about it since there were more pressing matters at the time. However, I absolutely agree with you that we need to provide a consistent way to cite Rubi.

I suggest that we publish Rubi in the [The Journal of Open Source Software](https://joss.theoj.org/). This will provide a DOI and we have the chance to explain in a small overview paper, why Rubi is important. In addition, it is a win-win for everyone: Users have a definite reference that they can cite and Rubi will be more visible. I will report back.

**Comment by halirutan** [comment]
@JedStephens We have seen your [article on arxiv](https://arxiv.org/abs/1811.04892). At the moment, we have prepared a manuscript for JOSS and it is [currently under review there](https://github.com/openjournals/joss-reviews/issues/1073). When they accept the article for publication, you will have a DOI for referencing.

**Comment by halirutan** [comment]
@JedStephens Finally, we have an official paper about Rubi

[![DOI](http://joss.theoj.org/papers/10.21105/joss.01073/status.svg)](https://doi.org/10.21105/joss.01073)

You can now cite Rubi with BibTeX in the following way

```
@article{Rich2018,
  doi = {10.21105/joss.01073},
  url = {https://doi.org/10.21105/joss.01073},
  year  = {2018},
  month = {dec},
  publisher = {The Open Journal},
  volume = {3},
  number = {32},
  pages = {1073},
  author = {Albert Rich and Patrick Scheibe and Nasser Abbasi},
  title = {Rule-based integration: An extensive system of symbolic integration rules},
  journal = {Journal of Open Source Software}
}
```
